name: lo_form_exmple
description: An example demonstrating how to use LoForm.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lo_form:
    path: ../
  url_launcher: ^6.0.9

dev_dependencies:
  lint: ^1.0.0

flutter:
  uses-material-design: true
