include: package:lint/analysis_options_package.yaml

linter:
  rules:
    # Easier to type
    prefer_single_quotes: true

    # Better to know what's imported from local files and what's from dependencies
    prefer_relative_imports: true

    # Sometimes it's okay to use it
    avoid_positional_boolean_parameters: false