name: lo_form
description: Flutter forms without all the pain
version: 0.0.1
homepage: https://github.com/YoussefRaafatNasry/lo_form

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

