include: package:lint/analysis_options.yaml

linter:
  rules:
    # Easier to type
    prefer_single_quotes: true

    # Better to know what's imported from local files and what's from dependencies
    prefer_relative_imports: true

    # Needed for LoFormInfo class
    avoid_classes_with_only_static_members: false
