name: GitHub Pages

on:
  push:
    branches: [ master ]
    tags:
      - '**'
    paths:
      - 'website/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - uses: erickzanardo/flutter-gh-pages@v6
        with:
          workingDir: website