name: Main

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
      - uses: erickzanardo/flutter-gh-pages@v6
        with:
          workingDir: website